name: matrimony_app
# Combines features of both projects: About Page Demo and Matrimony App.
description: A Flutter project demonstrating a Matrimony app with About page features.
# Prevents accidental publishing to pub.dev.
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Dart SDK version
environment:
  sdk: '>=2.19.0 <4.0.0'

# Dependencies required for the app
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.17.0
  sqflite: ^2.4.1
  flutter_staggered_animations: ^1.1.1
  curved_navigation_bar: ^1.0.6
  shared_preferences: ^2.5.2

# Dev dependencies
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific settings
flutter:
  uses-material-design: true
  assets:
    - assets/images/

  # Uncomment and add assets if needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Uncomment and configure fonts if needed
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
